export enum AccountStatus {
    PENDING = 'PENDING',
    ACTIVE = 'ACTIVE',
    SUSPENDED = 'SUSPENDED',
    TERMINATED = 'TERMINATED',
}

export enum AppStatus {
    CONFIGURATION_ERROR = 1000,
    INVALID_TOKEN,
    ACCOUNT_PENDING,
    ACCOUNT_SUSPENDED,
    ACCOUNT_TERMINATED,
    BASIC_AUTH_ERROR,
    BASIC_AUTH_INVALID_PASSWORD,
}
